apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: abdulmoiz
spec:
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: backend
        image: 557690581016.dkr.ecr.us-east-1.amazonaws.com/backend:v-56
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_URI
            value: "mongodb://mongo:27017/mydatabase"
      imagePullSecrets:
        - name: ecr-secret-newww

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: abdulmoiz
spec:
  selector:
    tier: backend
  ports:
  - port: 5000
    targetPort: 5000
