apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: abdulmoiz
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: 557690581016.dkr.ecr.us-east-1.amazonaws.com/jenkins:frontend-17
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: my-secret

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: abdulmoiz
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort
