apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: abdulmoiz
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: 557690581016.dkr.ecr.us-east-1.amazonaws.com/location-mern:frontend
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: ecr-credentials

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: abdulmoiz
spec:
  selector:
    tier: frontend
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30001
  
