# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Set environment variables for MongoDB (optional)
# ENV MONGO_INITDB_ROOT_USERNAME=admin
# ENV MONGO_INITDB_ROOT_PASSWORD=secret

# Expose MongoDB's default port
EXPOSE 27017

# Command to run MongoDB when the container starts
CMD ["mongod"]
